language: go

go:
  - "1.x"
  - "1.8"
  - "1.10.x"
  - master

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only

script:
  - go test ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
