// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	A
	AOneOffs
	MsgWithEmpty
	Empty
	B
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SomeEnum int32

const (
	SomeEnum_Val1 SomeEnum = 0
	SomeEnum_Val2 SomeEnum = 1
)

var SomeEnum_name = map[int32]string{
	0: "Val1",
	1: "Val2",
}
var SomeEnum_value = map[string]int32{
	"Val1": 0,
	"Val2": 1,
}

func (x SomeEnum) String() string {
	return proto.EnumName(SomeEnum_name, int32(x))
}
func (SomeEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ASomeEnum3 int32

const (
	A_Val5 ASomeEnum3 = 0
	A_Val6 ASomeEnum3 = 1
)

var ASomeEnum3_name = map[int32]string{
	0: "Val5",
	1: "Val6",
}
var ASomeEnum3_value = map[string]int32{
	"Val5": 0,
	"Val6": 1,
}

func (x ASomeEnum3) String() string {
	return proto.EnumName(ASomeEnum3_name, int32(x))
}
func (ASomeEnum3) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type A struct {
	MapEnum            map[int32]SomeEnum                   `protobuf:"bytes,1,rep,name=map_enum,json=mapEnum" json:"map_enum,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=example.SomeEnum"`
	MapScalar          map[int32]int32                      `protobuf:"bytes,2,rep,name=map_scalar,json=mapScalar" json:"map_scalar,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapMsg             map[int32]*google_protobuf.Timestamp `protobuf:"bytes,3,rep,name=map_msg,json=mapMsg" json:"map_msg,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RMsg               []*google_protobuf.Timestamp         `protobuf:"bytes,4,rep,name=r_msg,json=rMsg" json:"r_msg,omitempty"`
	RScalar            []int32                              `protobuf:"varint,5,rep,packed,name=r_scalar,json=rScalar" json:"r_scalar,omitempty"`
	REnum              []SomeEnum                           `protobuf:"varint,6,rep,packed,name=r_enum,json=rEnum,enum=example.SomeEnum" json:"r_enum,omitempty"`
	NREnum             ASomeEnum3                           `protobuf:"varint,7,opt,name=n_r_enum,json=nREnum,enum=example.ASomeEnum3" json:"n_r_enum,omitempty"`
	NRScalar           int32                                `protobuf:"varint,8,opt,name=n_r_scalar,json=nRScalar" json:"n_r_scalar,omitempty"`
	NRMsg              *google_protobuf.Timestamp           `protobuf:"bytes,9,opt,name=n_r_msg,json=nRMsg" json:"n_r_msg,omitempty"`
	ScalarFromContext  int32                                `protobuf:"varint,10,opt,name=scalar_from_context,json=scalarFromContext" json:"scalar_from_context,omitempty"`
	EnumFromContext    SomeEnum                             `protobuf:"varint,11,opt,name=enum_from_context,json=enumFromContext,enum=example.SomeEnum" json:"enum_from_context,omitempty"`
	MessageFromContext *google_protobuf.Timestamp           `protobuf:"bytes,12,opt,name=message_from_context,json=messageFromContext" json:"message_from_context,omitempty"`
	//    repeated bytes r_bytes = 13; // TODO
	//    bytes n_r_bytes = 14; // TODO
	MessageWithOneoffs *AOneOffs `protobuf:"bytes,13,opt,name=message_with_oneoffs,json=messageWithOneoffs" json:"message_with_oneoffs,omitempty"`
}

func (m *A) Reset()                    { *m = A{} }
func (m *A) String() string            { return proto.CompactTextString(m) }
func (*A) ProtoMessage()               {}
func (*A) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *A) GetMapEnum() map[int32]SomeEnum {
	if m != nil {
		return m.MapEnum
	}
	return nil
}

func (m *A) GetMapScalar() map[int32]int32 {
	if m != nil {
		return m.MapScalar
	}
	return nil
}

func (m *A) GetMapMsg() map[int32]*google_protobuf.Timestamp {
	if m != nil {
		return m.MapMsg
	}
	return nil
}

func (m *A) GetRMsg() []*google_protobuf.Timestamp {
	if m != nil {
		return m.RMsg
	}
	return nil
}

func (m *A) GetRScalar() []int32 {
	if m != nil {
		return m.RScalar
	}
	return nil
}

func (m *A) GetREnum() []SomeEnum {
	if m != nil {
		return m.REnum
	}
	return nil
}

func (m *A) GetNREnum() ASomeEnum3 {
	if m != nil {
		return m.NREnum
	}
	return A_Val5
}

func (m *A) GetNRScalar() int32 {
	if m != nil {
		return m.NRScalar
	}
	return 0
}

func (m *A) GetNRMsg() *google_protobuf.Timestamp {
	if m != nil {
		return m.NRMsg
	}
	return nil
}

func (m *A) GetScalarFromContext() int32 {
	if m != nil {
		return m.ScalarFromContext
	}
	return 0
}

func (m *A) GetEnumFromContext() SomeEnum {
	if m != nil {
		return m.EnumFromContext
	}
	return SomeEnum_Val1
}

func (m *A) GetMessageFromContext() *google_protobuf.Timestamp {
	if m != nil {
		return m.MessageFromContext
	}
	return nil
}

func (m *A) GetMessageWithOneoffs() *AOneOffs {
	if m != nil {
		return m.MessageWithOneoffs
	}
	return nil
}

type AOneOffs struct {
	// Types that are valid to be assigned to FirstEnum:
	//	*AOneOffs_ENREnum
	//	*AOneOffs_ENRScalar
	//	*AOneOffs_ENRMsg
	FirstEnum isAOneOffs_FirstEnum `protobuf_oneof:"firstEnum"`
	// Types that are valid to be assigned to FirstScalar:
	//	*AOneOffs_SNRScalar
	//	*AOneOffs_SNREnum
	//	*AOneOffs_SNRMsg
	FirstScalar isAOneOffs_FirstScalar `protobuf_oneof:"firstScalar"`
	// Types that are valid to be assigned to FirstMessage:
	//	*AOneOffs_MNRMsg
	//	*AOneOffs_MNRScalar
	//	*AOneOffs_MNREnum
	FirstMessage isAOneOffs_FirstMessage `protobuf_oneof:"firstMessage"`
}

func (m *AOneOffs) Reset()                    { *m = AOneOffs{} }
func (m *AOneOffs) String() string            { return proto.CompactTextString(m) }
func (*AOneOffs) ProtoMessage()               {}
func (*AOneOffs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isAOneOffs_FirstEnum interface {
	isAOneOffs_FirstEnum()
}
type isAOneOffs_FirstScalar interface {
	isAOneOffs_FirstScalar()
}
type isAOneOffs_FirstMessage interface {
	isAOneOffs_FirstMessage()
}

type AOneOffs_ENREnum struct {
	ENREnum SomeEnum `protobuf:"varint,7,opt,name=e_n_r_enum,json=eNREnum,enum=example.SomeEnum,oneof"`
}
type AOneOffs_ENRScalar struct {
	ENRScalar int32 `protobuf:"varint,8,opt,name=e_n_r_scalar,json=eNRScalar,oneof"`
}
type AOneOffs_ENRMsg struct {
	ENRMsg *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=e_n_r_msg,json=eNRMsg,oneof"`
}
type AOneOffs_SNRScalar struct {
	SNRScalar int32 `protobuf:"varint,10,opt,name=s_n_r_scalar,json=sNRScalar,oneof"`
}
type AOneOffs_SNREnum struct {
	SNREnum SomeEnum `protobuf:"varint,11,opt,name=s_n_r_enum,json=sNREnum,enum=example.SomeEnum,oneof"`
}
type AOneOffs_SNRMsg struct {
	SNRMsg *google_protobuf.Timestamp `protobuf:"bytes,12,opt,name=s_n_r_msg,json=sNRMsg,oneof"`
}
type AOneOffs_MNRMsg struct {
	MNRMsg *google_protobuf.Timestamp `protobuf:"bytes,13,opt,name=m_n_r_msg,json=mNRMsg,oneof"`
}
type AOneOffs_MNRScalar struct {
	MNRScalar int32 `protobuf:"varint,14,opt,name=m_n_r_scalar,json=mNRScalar,oneof"`
}
type AOneOffs_MNREnum struct {
	MNREnum SomeEnum `protobuf:"varint,15,opt,name=m_n_r_enum,json=mNREnum,enum=example.SomeEnum,oneof"`
}

func (*AOneOffs_ENREnum) isAOneOffs_FirstEnum()      {}
func (*AOneOffs_ENRScalar) isAOneOffs_FirstEnum()    {}
func (*AOneOffs_ENRMsg) isAOneOffs_FirstEnum()       {}
func (*AOneOffs_SNRScalar) isAOneOffs_FirstScalar()  {}
func (*AOneOffs_SNREnum) isAOneOffs_FirstScalar()    {}
func (*AOneOffs_SNRMsg) isAOneOffs_FirstScalar()     {}
func (*AOneOffs_MNRMsg) isAOneOffs_FirstMessage()    {}
func (*AOneOffs_MNRScalar) isAOneOffs_FirstMessage() {}
func (*AOneOffs_MNREnum) isAOneOffs_FirstMessage()   {}

func (m *AOneOffs) GetFirstEnum() isAOneOffs_FirstEnum {
	if m != nil {
		return m.FirstEnum
	}
	return nil
}
func (m *AOneOffs) GetFirstScalar() isAOneOffs_FirstScalar {
	if m != nil {
		return m.FirstScalar
	}
	return nil
}
func (m *AOneOffs) GetFirstMessage() isAOneOffs_FirstMessage {
	if m != nil {
		return m.FirstMessage
	}
	return nil
}

func (m *AOneOffs) GetENREnum() SomeEnum {
	if x, ok := m.GetFirstEnum().(*AOneOffs_ENREnum); ok {
		return x.ENREnum
	}
	return SomeEnum_Val1
}

func (m *AOneOffs) GetENRScalar() int32 {
	if x, ok := m.GetFirstEnum().(*AOneOffs_ENRScalar); ok {
		return x.ENRScalar
	}
	return 0
}

func (m *AOneOffs) GetENRMsg() *google_protobuf.Timestamp {
	if x, ok := m.GetFirstEnum().(*AOneOffs_ENRMsg); ok {
		return x.ENRMsg
	}
	return nil
}

func (m *AOneOffs) GetSNRScalar() int32 {
	if x, ok := m.GetFirstScalar().(*AOneOffs_SNRScalar); ok {
		return x.SNRScalar
	}
	return 0
}

func (m *AOneOffs) GetSNREnum() SomeEnum {
	if x, ok := m.GetFirstScalar().(*AOneOffs_SNREnum); ok {
		return x.SNREnum
	}
	return SomeEnum_Val1
}

func (m *AOneOffs) GetSNRMsg() *google_protobuf.Timestamp {
	if x, ok := m.GetFirstScalar().(*AOneOffs_SNRMsg); ok {
		return x.SNRMsg
	}
	return nil
}

func (m *AOneOffs) GetMNRMsg() *google_protobuf.Timestamp {
	if x, ok := m.GetFirstMessage().(*AOneOffs_MNRMsg); ok {
		return x.MNRMsg
	}
	return nil
}

func (m *AOneOffs) GetMNRScalar() int32 {
	if x, ok := m.GetFirstMessage().(*AOneOffs_MNRScalar); ok {
		return x.MNRScalar
	}
	return 0
}

func (m *AOneOffs) GetMNREnum() SomeEnum {
	if x, ok := m.GetFirstMessage().(*AOneOffs_MNREnum); ok {
		return x.MNREnum
	}
	return SomeEnum_Val1
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AOneOffs) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AOneOffs_OneofMarshaler, _AOneOffs_OneofUnmarshaler, _AOneOffs_OneofSizer, []interface{}{
		(*AOneOffs_ENREnum)(nil),
		(*AOneOffs_ENRScalar)(nil),
		(*AOneOffs_ENRMsg)(nil),
		(*AOneOffs_SNRScalar)(nil),
		(*AOneOffs_SNREnum)(nil),
		(*AOneOffs_SNRMsg)(nil),
		(*AOneOffs_MNRMsg)(nil),
		(*AOneOffs_MNRScalar)(nil),
		(*AOneOffs_MNREnum)(nil),
	}
}

func _AOneOffs_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AOneOffs)
	// firstEnum
	switch x := m.FirstEnum.(type) {
	case *AOneOffs_ENREnum:
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ENREnum))
	case *AOneOffs_ENRScalar:
		b.EncodeVarint(8<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ENRScalar))
	case *AOneOffs_ENRMsg:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ENRMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AOneOffs.FirstEnum has unexpected type %T", x)
	}
	// firstScalar
	switch x := m.FirstScalar.(type) {
	case *AOneOffs_SNRScalar:
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.SNRScalar))
	case *AOneOffs_SNREnum:
		b.EncodeVarint(11<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.SNREnum))
	case *AOneOffs_SNRMsg:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SNRMsg); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("AOneOffs.FirstScalar has unexpected type %T", x)
	}
	// firstMessage
	switch x := m.FirstMessage.(type) {
	case *AOneOffs_MNRMsg:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MNRMsg); err != nil {
			return err
		}
	case *AOneOffs_MNRScalar:
		b.EncodeVarint(14<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MNRScalar))
	case *AOneOffs_MNREnum:
		b.EncodeVarint(15<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MNREnum))
	case nil:
	default:
		return fmt.Errorf("AOneOffs.FirstMessage has unexpected type %T", x)
	}
	return nil
}

func _AOneOffs_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AOneOffs)
	switch tag {
	case 7: // firstEnum.e_n_r_enum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstEnum = &AOneOffs_ENREnum{SomeEnum(x)}
		return true, err
	case 8: // firstEnum.e_n_r_scalar
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstEnum = &AOneOffs_ENRScalar{int32(x)}
		return true, err
	case 9: // firstEnum.e_n_r_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Timestamp)
		err := b.DecodeMessage(msg)
		m.FirstEnum = &AOneOffs_ENRMsg{msg}
		return true, err
	case 10: // firstScalar.s_n_r_scalar
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstScalar = &AOneOffs_SNRScalar{int32(x)}
		return true, err
	case 11: // firstScalar.s_n_r_enum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstScalar = &AOneOffs_SNREnum{SomeEnum(x)}
		return true, err
	case 12: // firstScalar.s_n_r_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Timestamp)
		err := b.DecodeMessage(msg)
		m.FirstScalar = &AOneOffs_SNRMsg{msg}
		return true, err
	case 13: // firstMessage.m_n_r_msg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Timestamp)
		err := b.DecodeMessage(msg)
		m.FirstMessage = &AOneOffs_MNRMsg{msg}
		return true, err
	case 14: // firstMessage.m_n_r_scalar
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstMessage = &AOneOffs_MNRScalar{int32(x)}
		return true, err
	case 15: // firstMessage.m_n_r_enum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.FirstMessage = &AOneOffs_MNREnum{SomeEnum(x)}
		return true, err
	default:
		return false, nil
	}
}

func _AOneOffs_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AOneOffs)
	// firstEnum
	switch x := m.FirstEnum.(type) {
	case *AOneOffs_ENREnum:
		n += proto.SizeVarint(7<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.ENREnum))
	case *AOneOffs_ENRScalar:
		n += proto.SizeVarint(8<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.ENRScalar))
	case *AOneOffs_ENRMsg:
		s := proto.Size(x.ENRMsg)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// firstScalar
	switch x := m.FirstScalar.(type) {
	case *AOneOffs_SNRScalar:
		n += proto.SizeVarint(10<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.SNRScalar))
	case *AOneOffs_SNREnum:
		n += proto.SizeVarint(11<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.SNREnum))
	case *AOneOffs_SNRMsg:
		s := proto.Size(x.SNRMsg)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// firstMessage
	switch x := m.FirstMessage.(type) {
	case *AOneOffs_MNRMsg:
		s := proto.Size(x.MNRMsg)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *AOneOffs_MNRScalar:
		n += proto.SizeVarint(14<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.MNRScalar))
	case *AOneOffs_MNREnum:
		n += proto.SizeVarint(15<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.MNREnum))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MsgWithEmpty struct {
	EmptyField *Empty `protobuf:"bytes,1,opt,name=empty_field,json=emptyField" json:"empty_field,omitempty"`
}

func (m *MsgWithEmpty) Reset()                    { *m = MsgWithEmpty{} }
func (m *MsgWithEmpty) String() string            { return proto.CompactTextString(m) }
func (*MsgWithEmpty) ProtoMessage()               {}
func (*MsgWithEmpty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgWithEmpty) GetEmptyField() *Empty {
	if m != nil {
		return m.EmptyField
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type B struct {
	MapEnum   map[int32]SomeEnum                   `protobuf:"bytes,1,rep,name=map_enum,json=mapEnum" json:"map_enum,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=example.SomeEnum"`
	MapScalar map[int32]int32                      `protobuf:"bytes,2,rep,name=map_scalar,json=mapScalar" json:"map_scalar,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapMsg    map[int32]*google_protobuf.Timestamp `protobuf:"bytes,3,rep,name=map_msg,json=mapMsg" json:"map_msg,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RMsg      []*google_protobuf.Timestamp         `protobuf:"bytes,4,rep,name=r_msg,json=rMsg" json:"r_msg,omitempty"`
	RScalar   []int32                              `protobuf:"varint,5,rep,packed,name=r_scalar,json=rScalar" json:"r_scalar,omitempty"`
	REnum     []SomeEnum                           `protobuf:"varint,6,rep,packed,name=r_enum,json=rEnum,enum=example.SomeEnum" json:"r_enum,omitempty"`
	NREnum    SomeEnum                             `protobuf:"varint,7,opt,name=n_r_enum,json=nREnum,enum=example.SomeEnum" json:"n_r_enum,omitempty"`
	NRScalar  int32                                `protobuf:"varint,8,opt,name=n_r_scalar,json=nRScalar" json:"n_r_scalar,omitempty"`
	NRMsg     *google_protobuf.Timestamp           `protobuf:"bytes,9,opt,name=n_r_msg,json=nRMsg" json:"n_r_msg,omitempty"`
}

func (m *B) Reset()                    { *m = B{} }
func (m *B) String() string            { return proto.CompactTextString(m) }
func (*B) ProtoMessage()               {}
func (*B) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *B) GetMapEnum() map[int32]SomeEnum {
	if m != nil {
		return m.MapEnum
	}
	return nil
}

func (m *B) GetMapScalar() map[int32]int32 {
	if m != nil {
		return m.MapScalar
	}
	return nil
}

func (m *B) GetMapMsg() map[int32]*google_protobuf.Timestamp {
	if m != nil {
		return m.MapMsg
	}
	return nil
}

func (m *B) GetRMsg() []*google_protobuf.Timestamp {
	if m != nil {
		return m.RMsg
	}
	return nil
}

func (m *B) GetRScalar() []int32 {
	if m != nil {
		return m.RScalar
	}
	return nil
}

func (m *B) GetREnum() []SomeEnum {
	if m != nil {
		return m.REnum
	}
	return nil
}

func (m *B) GetNREnum() SomeEnum {
	if m != nil {
		return m.NREnum
	}
	return SomeEnum_Val1
}

func (m *B) GetNRScalar() int32 {
	if m != nil {
		return m.NRScalar
	}
	return 0
}

func (m *B) GetNRMsg() *google_protobuf.Timestamp {
	if m != nil {
		return m.NRMsg
	}
	return nil
}

func init() {
	proto.RegisterType((*A)(nil), "example.A")
	proto.RegisterType((*AOneOffs)(nil), "example.AOneOffs")
	proto.RegisterType((*MsgWithEmpty)(nil), "example.MsgWithEmpty")
	proto.RegisterType((*Empty)(nil), "example.Empty")
	proto.RegisterType((*B)(nil), "example.B")
	proto.RegisterEnum("example.SomeEnum", SomeEnum_name, SomeEnum_value)
	proto.RegisterEnum("example.ASomeEnum3", ASomeEnum3_name, ASomeEnum3_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ServiceExample service

type ServiceExampleClient interface {
	GetQueryMethod(ctx context.Context, in *AOneOffs, opts ...grpc.CallOption) (*B, error)
	MutationMethod(ctx context.Context, in *B, opts ...grpc.CallOption) (*A, error)
	QueryMethod(ctx context.Context, in *A, opts ...grpc.CallOption) (*B, error)
	GetMutatuionMethod(ctx context.Context, in *MsgWithEmpty, opts ...grpc.CallOption) (*MsgWithEmpty, error)
	GetEmptiesMsg(ctx context.Context, in *google_protobuf.Timestamp, opts ...grpc.CallOption) (*Empty, error)
}

type serviceExampleClient struct {
	cc *grpc.ClientConn
}

func NewServiceExampleClient(cc *grpc.ClientConn) ServiceExampleClient {
	return &serviceExampleClient{cc}
}

func (c *serviceExampleClient) GetQueryMethod(ctx context.Context, in *AOneOffs, opts ...grpc.CallOption) (*B, error) {
	out := new(B)
	err := grpc.Invoke(ctx, "/example.ServiceExample/getQueryMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExampleClient) MutationMethod(ctx context.Context, in *B, opts ...grpc.CallOption) (*A, error) {
	out := new(A)
	err := grpc.Invoke(ctx, "/example.ServiceExample/mutationMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExampleClient) QueryMethod(ctx context.Context, in *A, opts ...grpc.CallOption) (*B, error) {
	out := new(B)
	err := grpc.Invoke(ctx, "/example.ServiceExample/queryMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExampleClient) GetMutatuionMethod(ctx context.Context, in *MsgWithEmpty, opts ...grpc.CallOption) (*MsgWithEmpty, error) {
	out := new(MsgWithEmpty)
	err := grpc.Invoke(ctx, "/example.ServiceExample/getMutatuionMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceExampleClient) GetEmptiesMsg(ctx context.Context, in *google_protobuf.Timestamp, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/example.ServiceExample/getEmptiesMsg", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ServiceExample service

type ServiceExampleServer interface {
	GetQueryMethod(context.Context, *AOneOffs) (*B, error)
	MutationMethod(context.Context, *B) (*A, error)
	QueryMethod(context.Context, *A) (*B, error)
	GetMutatuionMethod(context.Context, *MsgWithEmpty) (*MsgWithEmpty, error)
	GetEmptiesMsg(context.Context, *google_protobuf.Timestamp) (*Empty, error)
}

func RegisterServiceExampleServer(s *grpc.Server, srv ServiceExampleServer) {
	s.RegisterService(&_ServiceExample_serviceDesc, srv)
}

func _ServiceExample_GetQueryMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AOneOffs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExampleServer).GetQueryMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ServiceExample/GetQueryMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExampleServer).GetQueryMethod(ctx, req.(*AOneOffs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExample_MutationMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(B)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExampleServer).MutationMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ServiceExample/MutationMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExampleServer).MutationMethod(ctx, req.(*B))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExample_QueryMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(A)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExampleServer).QueryMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ServiceExample/QueryMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExampleServer).QueryMethod(ctx, req.(*A))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExample_GetMutatuionMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExampleServer).GetMutatuionMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ServiceExample/GetMutatuionMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExampleServer).GetMutatuionMethod(ctx, req.(*MsgWithEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceExample_GetEmptiesMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Timestamp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceExampleServer).GetEmptiesMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ServiceExample/GetEmptiesMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceExampleServer).GetEmptiesMsg(ctx, req.(*google_protobuf.Timestamp))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceExample_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.ServiceExample",
	HandlerType: (*ServiceExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getQueryMethod",
			Handler:    _ServiceExample_GetQueryMethod_Handler,
		},
		{
			MethodName: "mutationMethod",
			Handler:    _ServiceExample_MutationMethod_Handler,
		},
		{
			MethodName: "queryMethod",
			Handler:    _ServiceExample_QueryMethod_Handler,
		},
		{
			MethodName: "getMutatuionMethod",
			Handler:    _ServiceExample_GetMutatuionMethod_Handler,
		},
		{
			MethodName: "getEmptiesMsg",
			Handler:    _ServiceExample_GetEmptiesMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 816 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x55, 0xed, 0x8e, 0xdb, 0x44,
	0x14, 0x5d, 0x27, 0xeb, 0xaf, 0xeb, 0xac, 0x9b, 0x1d, 0x16, 0x48, 0x23, 0x44, 0xd3, 0x48, 0x88,
	0x08, 0x24, 0x67, 0x71, 0x05, 0x5b, 0xf1, 0x21, 0x94, 0x54, 0xa9, 0xf2, 0x83, 0xec, 0x8a, 0x29,
	0x1f, 0x3f, 0x2d, 0x77, 0x3b, 0xf6, 0x5a, 0x64, 0xec, 0xe0, 0x99, 0x94, 0xe6, 0x39, 0x78, 0x02,
	0xde, 0x8c, 0xf7, 0xe0, 0x0f, 0x9a, 0x19, 0xdb, 0x99, 0x74, 0xb3, 0x0d, 0xaa, 0x84, 0x84, 0xc4,
	0xbf, 0xb9, 0xbe, 0xe7, 0x9c, 0xb9, 0xc7, 0x39, 0xbe, 0x01, 0xe0, 0x84, 0xf1, 0x60, 0x55, 0x16,
	0xbc, 0x40, 0x36, 0x79, 0x15, 0xd3, 0xd5, 0x92, 0xf4, 0x1f, 0xa4, 0x45, 0x91, 0x2e, 0xc9, 0x58,
	0x3e, 0x7e, 0xbe, 0x4e, 0xc6, 0x3c, 0xa3, 0x84, 0xf1, 0x98, 0xae, 0x14, 0x72, 0xf8, 0x87, 0x0d,
	0xc6, 0x04, 0x85, 0xe0, 0xd0, 0x78, 0x15, 0x91, 0x7c, 0x4d, 0x7b, 0xc6, 0xa0, 0x3d, 0xf2, 0xc2,
	0xf7, 0x83, 0x4a, 0x22, 0x98, 0x04, 0x8b, 0x78, 0x35, 0xcb, 0xd7, 0x74, 0x96, 0xf3, 0x72, 0x83,
	0x6d, 0xaa, 0x2a, 0xf4, 0x18, 0x40, 0x70, 0xd8, 0x75, 0xbc, 0x8c, 0xcb, 0x5e, 0x4b, 0xb2, 0xee,
	0xef, 0xb2, 0x9e, 0xc9, 0x9e, 0xe2, 0xb9, 0xb4, 0xae, 0xd1, 0x18, 0x84, 0x48, 0x44, 0x59, 0xda,
	0x6b, 0x4b, 0xda, 0x7b, 0xbb, 0xb4, 0x05, 0x4b, 0x15, 0xc7, 0xa2, 0xb2, 0x40, 0x63, 0x30, 0x4b,
	0x09, 0x3f, 0x96, 0xf0, 0x7e, 0xa0, 0x5c, 0x05, 0xb5, 0xab, 0xe0, 0x87, 0xda, 0x15, 0x3e, 0x2e,
	0x05, 0xe1, 0x3e, 0x38, 0x65, 0x3d, 0x99, 0x39, 0x68, 0x8f, 0x4c, 0x6c, 0x97, 0xd5, 0xe5, 0x23,
	0xb0, 0x4a, 0x65, 0xd4, 0x1a, 0xb4, 0x47, 0x7e, 0x78, 0xda, 0xdc, 0xcd, 0x0a, 0x4a, 0x84, 0x33,
	0x6c, 0x96, 0xd2, 0x60, 0x00, 0x4e, 0x1e, 0x55, 0x58, 0x7b, 0x60, 0x8c, 0xfc, 0xf0, 0x4c, 0x9b,
	0xb3, 0x46, 0x3f, 0xc2, 0x56, 0x8e, 0x25, 0xfe, 0x03, 0x00, 0x81, 0xaf, 0xae, 0x75, 0x06, 0xc6,
	0xc8, 0xc4, 0x4e, 0x8e, 0xab, 0x7b, 0x43, 0xb0, 0x45, 0x57, 0xb8, 0x70, 0x07, 0xc6, 0x01, 0x17,
	0x66, 0x8e, 0x85, 0x8d, 0x00, 0xde, 0x51, 0x6a, 0x51, 0x52, 0x16, 0x34, 0xba, 0x2e, 0x72, 0x4e,
	0x5e, 0xf1, 0x1e, 0x48, 0xe9, 0x53, 0xd5, 0x7a, 0x5a, 0x16, 0xf4, 0x89, 0x6a, 0xa0, 0x6f, 0xe0,
	0x54, 0x4c, 0xbb, 0x8b, 0xf6, 0xe4, 0xe8, 0x7b, 0x6c, 0xde, 0x13, 0x58, 0x9d, 0xfe, 0x1d, 0x9c,
	0x51, 0xc2, 0x58, 0x9c, 0x92, 0x5d, 0x85, 0xce, 0xc1, 0x79, 0x51, 0xc5, 0xd3, 0xd5, 0x9e, 0x6c,
	0xd5, 0x7e, 0xcb, 0xf8, 0x4d, 0x54, 0xe4, 0xa4, 0x48, 0x12, 0xd6, 0x3b, 0x91, 0x6a, 0xdb, 0x79,
	0x26, 0x57, 0x39, 0xb9, 0x4a, 0x12, 0xd6, 0x88, 0xfc, 0x9c, 0xf1, 0x9b, 0x2b, 0x05, 0xee, 0x2f,
	0xa0, 0xa3, 0xa7, 0x0f, 0x75, 0xa1, 0xfd, 0x0b, 0xd9, 0xf4, 0x0c, 0xf9, 0x06, 0xc4, 0x11, 0x7d,
	0x0c, 0xe6, 0xcb, 0x78, 0xb9, 0x26, 0xbd, 0xd6, 0x5d, 0x3e, 0x55, 0xff, 0xcb, 0xd6, 0x63, 0xa3,
	0xff, 0x35, 0xf8, 0xbb, 0xb1, 0xdc, 0x23, 0x78, 0xa6, 0x0b, 0x9a, 0x3a, 0xfb, 0x47, 0xf0, 0xb4,
	0x74, 0xee, 0xa1, 0x9e, 0xeb, 0xd4, 0x03, 0xbf, 0x70, 0x23, 0x3b, 0x7c, 0x00, 0x6e, 0x13, 0x26,
	0xe4, 0xc0, 0xf1, 0x4f, 0xf1, 0xf2, 0xf3, 0xee, 0x51, 0x75, 0xfa, 0xa2, 0x6b, 0x0c, 0xff, 0x6c,
	0x83, 0x53, 0xbf, 0x25, 0x74, 0x0e, 0x40, 0xa2, 0xd7, 0x72, 0x79, 0xdb, 0xf4, 0xfc, 0x08, 0xdb,
	0xe4, 0x52, 0xe5, 0xf2, 0x21, 0x74, 0x14, 0x43, 0x4f, 0xe6, 0xfc, 0x08, 0xbb, 0xe4, 0xb2, 0x0e,
	0xe7, 0x05, 0xb8, 0x0a, 0xf2, 0x8f, 0xe2, 0x39, 0x3f, 0xc2, 0x16, 0xb9, 0x94, 0x09, 0x7d, 0x08,
	0x1d, 0xa6, 0x6b, 0xcb, 0x68, 0xce, 0x0d, 0xec, 0xb2, 0x46, 0xfb, 0x1c, 0x80, 0x6d, 0x07, 0xbe,
	0x2b, 0x8d, 0x73, 0x03, 0xdb, 0xac, 0x1a, 0xf8, 0x02, 0x5c, 0xd6, 0x4c, 0x73, 0x30, 0x7c, 0x73,
	0x03, 0x5b, 0x4c, 0x4d, 0x73, 0x01, 0x2e, 0x6d, 0x88, 0x27, 0x07, 0x89, 0x2d, 0x6c, 0xd1, 0xc6,
	0x06, 0xd5, 0x6d, 0xf8, 0xd2, 0x46, 0x0b, 0xbb, 0x54, 0xb7, 0x41, 0xb7, 0x36, 0xee, 0xdd, 0x65,
	0xa3, 0x85, 0x6d, 0xaa, 0x6c, 0x4c, 0x3d, 0x70, 0x93, 0xac, 0x64, 0x5c, 0x16, 0x27, 0xe0, 0xc9,
	0x42, 0xa9, 0x4d, 0x7d, 0xe8, 0xc8, 0x72, 0xa1, 0x22, 0x3f, 0xfc, 0x16, 0x3a, 0x0b, 0x96, 0x8a,
	0xe4, 0xcf, 0xe8, 0x8a, 0x6f, 0xd0, 0x18, 0x3c, 0x22, 0x0e, 0x51, 0x92, 0x91, 0xe5, 0x0b, 0x99,
	0x31, 0x2f, 0xf4, 0x9b, 0xeb, 0x24, 0x08, 0x83, 0x84, 0x3c, 0x15, 0x88, 0xa1, 0x0d, 0xa6, 0x7c,
	0x38, 0xfc, 0xeb, 0x18, 0x8c, 0xe9, 0x1b, 0x17, 0xfa, 0xf4, 0xad, 0x16, 0xfa, 0xf4, 0xed, 0x16,
	0xfa, 0xf4, 0x3f, 0xb4, 0xd0, 0x3f, 0xbd, 0xb5, 0xd0, 0xf7, 0x60, 0xff, 0xb5, 0x6d, 0xfe, 0x7f,
	0xd8, 0x65, 0x9f, 0x7c, 0x08, 0x4e, 0x3d, 0x6b, 0xb5, 0xc0, 0x3e, 0x6b, 0x56, 0x59, 0xd8, 0x35,
	0xc2, 0xdf, 0x5b, 0xe0, 0x3f, 0x23, 0xe5, 0xcb, 0xec, 0x9a, 0xcc, 0x94, 0x37, 0x34, 0x06, 0x3f,
	0x25, 0xfc, 0xfb, 0x35, 0x29, 0x37, 0x0b, 0xc2, 0x6f, 0x8a, 0x17, 0xe8, 0xf6, 0x7f, 0x43, 0x1f,
	0xb6, 0x81, 0x42, 0x23, 0xf0, 0xe9, 0x9a, 0xc7, 0x3c, 0x2b, 0xf2, 0x8a, 0xa0, 0x75, 0x35, 0xe4,
	0x04, 0x7d, 0x04, 0xde, 0xaf, 0x9a, 0xae, 0xd6, 0xda, 0x11, 0x9c, 0x02, 0x4a, 0x09, 0x5f, 0x08,
	0xcd, 0xf5, 0x56, 0xf4, 0xdd, 0x06, 0xa1, 0x7f, 0x99, 0xfd, 0xfd, 0x8f, 0xd1, 0x57, 0x70, 0x92,
	0x12, 0x2e, 0xce, 0x19, 0x61, 0x22, 0xb1, 0x6f, 0x78, 0x61, 0xfd, 0xd7, 0x3e, 0xe4, 0xe7, 0x96,
	0xc4, 0x3c, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x29, 0x3e, 0x27, 0x72, 0xc3, 0x09, 0x00, 0x00,
}
